import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'vi';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.home': 'Home',
    'nav.features': 'Features',
    'nav.pricing': 'Pricing',
    'nav.docs': 'Docs',
    'nav.blog': 'Blog',
    'nav.login': 'Login',
    'nav.signup': 'Sign Up',
    'nav.overview': 'Overview',
    'nav.bank': 'Bank',
    'nav.webhook': 'Webhook',
    'nav.billing': 'Billing',
    'nav.support': 'Support',
    'nav.admin': 'Admin Panel',
    'hero.title': 'Modern Finance for Everyone',
    'hero.subtitle': 'Moneta helps you manage your money, track expenses, and grow your wealth with ease.',
    'hero.cta': 'Get Started',
    'hero.users_active': 'Users Active',
    'hero.countries': 'Countries',
    'hero.finance_app': 'Finance App',
    'hero.cardholder': 'Cardholder',
    'dashboard.welcome': 'Welcome',
    'dashboard.balance': 'My Balance',
    'dashboard.spent': 'Monthly Spent',
    'dashboard.income': 'Monthly Income',
    'dashboard.compared': 'Compared to last month',
    'dashboard.transfer': 'Transfer',
    'dashboard.received': 'Received',
    'dashboard.cashflow': 'Cashflow',
    'dashboard.recent_activity': 'Recent Activity',
    'dashboard.expense': 'Expense',
    'dashboard.this_week': 'This Week',
    'dashboard.this_month': 'This Month',
    'dashboard.this_year': 'This Year',
    'dashboard.today': 'Today',
    'dashboard.notifications': 'Notifications',
    'dashboard.mark_read': 'Mark all as read',
    'dashboard.view_all': 'View all',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.columns': 'Columns',
    'common.save': 'Save Changes',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.actions': 'Actions',
    'common.status': 'Status',
    'common.date': 'Date',
    'common.amount': 'Amount',
    'common.loading': 'Loading...',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.create': 'Create',
    'common.back': 'Back',
    'common.copy': 'Copy',
    'auth.login_title': 'Welcome Back',
    'auth.login_subtitle': 'Enter your credentials to access your account',
    'auth.register_title': 'Create Account',
    'auth.register_subtitle': 'Join Moneta and start managing your finances',
    'auth.register_success': 'Registration successful! Please verify your email.',
    'auth.register_failed': 'Registration failed',
    'auth.login_success': 'Login successful!',
    'auth.login_failed': 'Login failed',
    'auth.verification_success': 'Verification successful!',
    'auth.email_verified': 'Email verified successfully!',
    'auth.code_sent': 'Verification code sent to your email',
    'auth.code_resent': 'Verification code resent successfully',
    'auth.verify_email_required': 'Please verify your email to continue',
    'auth.verify_login_required': 'Please verify this login from a new device',
    'auth.forgot_password': 'Forgot Password?',
    'auth.forgot_password_desc': "Enter your email address and we'll send you instructions to reset your password.",
    'auth.send_reset_link': 'Send Reset Link',
    'auth.back_to_login': 'Back to Login',
    'auth.no_account': "Don't have an account?",
    'auth.have_account': 'Already have an account?',
    'auth.email': 'Email Address',
    'auth.password': 'Password',
    'auth.full_name': 'Full Name',
    'auth.verify_title': 'Verify Account',
    'auth.verify_desc': 'We have sent a 6-digit OTP to your email. Please enter it to continue.',
    'auth.verify_email_title': 'Verify Your Email',
    'auth.verify_email_desc': "We've sent a 6-digit code to your email. Please enter it below.",
    'auth.verify_login_title': 'Verify Login',
    'auth.verify_login_desc': 'We detected a login from a new device. Please enter the 6-digit code sent to your email.',
    'auth.verify_2fa_title': 'Two-Factor Authentication',
    'auth.verify_2fa_desc': 'Enter the 6-digit code from your authenticator app.',
    'auth.resend': 'Resend code',
    'auth.resend_after': 'Resend code after',
    'auth.back_to_register': 'Back to registration',
    'auth.logout': 'Logout',
    'auth.passwords_do_not_match': 'Passwords do not match',
    'profile.title': 'User Profile',
    'profile.settings': 'Settings',
    'profile.personal': 'Personal Info',
    'profile.notifications': 'Notification Settings',
    'profile.security': 'Security Settings',
    'profile.linked': 'Linked Accounts',
    'profile.your_profile': 'Your Profile',
    'profile.phone': 'Phone Number',
    'profile.change_password': 'Change Password',
    'profile.current_password': 'Current Password',
    'profile.new_password': 'New Password',
    'profile.confirm_new_password': 'Confirm New Password',
    'profile.update_password': 'Update Password',
    'profile.email_notifs': 'Email Notifications',
    'profile.email_notifs_desc': 'Automatic updates sent to your primary email.',
    'profile.settings_updated': 'Settings updated successfully!',
    'profile.profile_updated': 'Profile updated successfully!',
    'profile.password_changed': 'Password changed successfully!',
    'profile.device_removed': 'Device removed successfully!',
    'profile.notif_success_title': 'Payment Success',
    'profile.notif_success_desc': 'Receive an email for every successful payment transaction.',
    'profile.notif_failed_title': 'Payment Failed',
    'profile.notif_failed_desc': 'Get notified immediately when a payment attempt fails.',
    'profile.notif_dispute_title': 'Disputes',
    'profile.notif_dispute_desc': 'Receive alerts for new disputes and evidence deadlines.',
    'profile.notif_payout_title': 'Payouts',
    'profile.notif_payout_desc': 'Get notified when funds are sent to your bank account.',
    'profile.notif_member_title': 'New Member',
    'profile.notif_member_desc': 'Receive confirmation when a new member joins the team.',
    'profile.login_alerts': 'Login Alerts',
    'profile.login_alerts_desc': 'Get notified when there is a login from a new device or location.',
    'profile.trusted_devices': 'Trusted Devices',
    'profile.login_history': 'Login History',
    'profile.device': 'Device',
    'profile.last_active': 'Last Active',
    'profile.remove_device': 'Remove Device',
    'profile.remove_device_confirm': 'Are you sure you want to remove this device from the trusted list?',
    'profile.ip_address': 'IP Address',
    'profile.location': 'Location',
    'profile.login_success': 'Success',
    'profile.login_failed': 'Failed',
    'profile.social_login': 'Social Login',
    'profile.social_login_desc': 'Link social accounts for faster login.',
    'profile.activity_notifs': 'Activity Notifications',
    'profile.activity_notifs_desc': 'Receive notifications via messaging apps.',
    'profile.linked_status': 'Linked',
    'profile.not_linked_status': 'Not Linked',
    'profile.unlink': 'Unlink',
    'profile.link_now': 'Link Now',
    'profile.verify_email': 'Verify Your Email',
    'profile.verify_email_desc': 'Please verify your email address to access all features.',
    'profile.send_verification_code': 'Send Verification Code',
    'profile.verify_email_modal_desc': 'Enter the 6-digit code sent to your email to verify your account.',
    'common.please_fill_all_fields': 'Please fill in all fields',
    'common.done': 'Done',
    'common.coming_soon': 'Coming soon',
    '2fa.title': 'Configure 2FA',
    '2fa.enabled': '2FA enabled successfully!',
    '2fa.disabled': '2FA disabled successfully!',
    '2fa.step1_title': 'Scan QR Code',
    '2fa.step1_desc': 'Use an authenticator app to scan the QR code below.',
    '2fa.step2_title': 'Enter Verification Code',
    '2fa.step2_desc': 'Enter the 6-digit code from your app to complete setup.',
    '2fa.manual_entry': 'Or enter code manually',
    '2fa.next': 'Next',
    '2fa.back': 'Back',
    '2fa.complete': 'Complete',
    'webhook.edit_title': 'Edit webhook endpoint',
    'webhook.create_title': 'Create webhook endpoint',
    'webhook.enabled': 'Enabled',
    'webhook.endpoint_desc': 'Endpoint must accept POST requests with a JSON body. URLs that only use GET (e.g. /me) will return a 404 when sending a webhook.',
    'webhook.signing_secret': 'Signing secret',
    'webhook.signing_secret_desc': 'Use this secret to verify that webhook events are actually sent from HyperPay.',
    'webhook.linked_bank': 'Linked bank account',
    'webhook.no_bank_found': 'No bank accounts found. Please add an account on the Banking page first.',
    'webhook.linked_bank_desc': 'If no account is selected, the webhook will receive events from all valid accounts.',
    'webhook.direction': 'Transaction direction',
    'webhook.direction_both': 'Both',
    'webhook.direction_in': 'Money in',
    'webhook.direction_out': 'Money out',
    'webhook.content_type': 'Content type',
    'webhook.retry_desc': 'Retry when response is not 2xx',
    'webhook.max_retries': 'Max retries',
    'webhook.auth': 'Authentication',
    'webhook.auth_type': 'Auth type',
    'webhook.auth_none': 'None',
    'webhook.auth_basic': 'Basic Auth',
    'webhook.auth_bearer': 'Bearer Token',
    'webhook.payment_code_rules': 'Payment code rules',
    'webhook.require_payment_code': 'Require payment code',
    'webhook.enable_extraction': 'Enable payment code extraction rule',
    'webhook.enable_endpoint': 'Enable this endpoint',
    'webhook.save': 'Save Configuration',
    'docs.title': 'API Documentation',
    'docs.getting_started': 'Getting Started',
    'docs.introduction': 'Introduction',
    'docs.authentication': 'Authentication',
    'docs.payments_api': 'Payments API',
    'docs.create_payment': 'Create a Payment',
    'docs.retrieve_payment': 'Retrieve a Payment',
    'docs.webhooks': 'Webhooks',
    'docs.handling_webhooks': 'Handling Webhooks',
    'docs.intro_desc': 'Welcome to the Moneta API. You can use our API to access Moneta API endpoints, which can get information on various database elements, create new payments, and securely manage your financial operations.',
    'docs.base_url': 'Base URL:',
    'docs.base_url_desc': 'All API requests should be made to the {url} base URL.',
    'docs.auth_desc1': 'The Moneta API uses API keys to authenticate requests. You can view and manage your API keys in the Moneta Dashboard.',
    'docs.auth_desc2': 'Authentication to the API is performed via HTTP Bearer Auth. Provide your API key as the bearer token value.',
    'docs.create_payment_desc': 'Creates a new payment object. This is the first step in the payment process.',
    'docs.endpoint': 'Endpoint',
    'docs.parameters': 'Parameters',
    'docs.param_amount_desc': 'A positive integer representing how much to charge in the smallest currency unit (e.g., 100 cents to charge $1.00).',
    'docs.param_currency_desc': 'Three-letter ISO currency code, in lowercase. Must be a supported currency.',
    'docs.example_request': 'Example Request',
    'docs.example_response': 'Example Response',
    'docs.webhooks_desc': 'Moneta uses webhooks to notify your application when an event happens in your account. Webhooks are particularly useful for asynchronous events like when a customer\'s bank confirms a payment.',
    'docs.verifying_signatures': 'Verifying Signatures',
    'docs.verifying_signatures_desc': 'We strongly recommend verifying webhook signatures to ensure that the events were sent by Moneta, not by a third party.',
    'blog.back': 'Back to Blog',
    'blog.author_role': 'CEO & Founder',
    'blog.tags': 'Tags',
    'blog.share': 'Share',
    'blog.landscape_title': 'The Current Landscape',
    'blog.looking_ahead': 'Looking Ahead',
    'blog.quote': '"The future of finance is not just about moving money faster, it\'s about making money smarter."',
    'support.title': 'Support Tickets',
    'support.placeholder_search': 'Search tickets...',
    'support.filter_title': 'Filter Tickets',
    'support.add': 'Create Ticket',
    'support.edit': 'Edit Ticket',
    'support.ticket_id': 'Ticket ID',
    'support.subject': 'Subject',
    'support.priority': 'Priority',
    'support.created_at': 'Created At',
    'support.category': 'Category',
    'support.description': 'Description',
    'support.placeholder_subject': 'Brief description of the issue',
    'support.placeholder_category': 'Select a category...',
    'support.placeholder_description': 'Please provide as much detail as possible...',
    'support.submit': 'Submit Ticket',
    'support.status_open': 'Open',
    'support.status_in_progress': 'In Progress',
    'support.status_closed': 'Closed',
    'support.priority_high': 'High',
    'support.priority_medium': 'Medium',
    'support.priority_low': 'Low',
    'support.cat_billing': 'Billing',
    'support.cat_technical': 'Technical Issue',
    'support.cat_account': 'Account Management',
    'support.cat_other': 'Other',
    'verify_otp.title': 'Verify your account',
    'verify_otp.desc': 'We\'ve sent a 6-digit verification code to your email. Please enter it below to continue.',
    'verify_otp.placeholder': 'Enter 6-digit code',
    'verify_otp.verify': 'Verify Account',
    'verify_otp.resend_prompt': 'Didn\'t receive the code?',
    'verify_otp.resend_button': 'Resend code',
    'verify_otp.resend_wait': 'Resend in',
    'verify_otp.back_to_login': 'Back to login',
    'bank.title': 'Bank Accounts',
    'bank.add': 'Add Bank',
    'bank.edit': 'Edit Bank Account',
    'bank.name': 'Bank Name',
    'bank.account_no': 'Account Number',
    'bank.type': 'Type',
    'bank.select': 'Select Bank',
    'bank.placeholder_search': 'Search bank accounts...',
    'bank.filter_title': 'Filter Accounts',
    'bank.all_banks': 'All Banks',
    'bank.creation_time': 'Creation Time',
    'bank.all_statuses': 'All Statuses',
    'bank.active': 'Active',
    'bank.inactive': 'Inactive',
    'bank.all_types': 'All Types',
    'bank.personal': 'Personal',
    'bank.business': 'Business',
    'bank.apply_filters': 'Apply Filters',
    'bank.reset': 'Reset',
    'bank.password': 'Password',
    'bank.password_placeholder': 'Enter password',
    'bank.password_edit_placeholder': 'Leave blank to keep current password',
    'webhook.title': 'Webhooks',
    'webhook.list': 'Webhook List',
    'webhook.logs': 'Event Logs',
    'webhook.add': 'Add Webhook',
    'webhook.endpoint_url': 'Endpoint URL',
    'webhook.events': 'Events',
    'webhook.placeholder_search': 'Search webhooks...',
    'webhook.placeholder_search_logs': 'Search logs...',
    'webhook.filter_title': 'Filter Webhooks',
    'webhook.event': 'Event',
    'billing.title': 'Billing & Plans',
    'billing.current_plan': 'Current Plan',
    'billing.pro_plan': 'Pro Plan',
    'billing.billed_monthly': 'Billed monthly. Next charge on Jun 1, 2024.',
    'billing.upgrade': 'Upgrade',
    'billing.cancel': 'Cancel',
    'billing.available_balance': 'Available Balance',
    'billing.auto_recharge': 'Auto-recharge',
    'billing.enabled_below': 'Enabled (below $50)',
    'billing.payment_method': 'Payment Method',
    'billing.add_funds': 'Add Funds',
    'billing.api_usage': 'API Usage',
    'billing.calls_limit': 'calls over the last 30 days',
    'billing.purchase_history': 'Purchase History',
    'billing.invoice_id': 'Invoice ID',
    'billing.plan_item': 'Plan / Item',
    'billing.amount': 'Amount',
    'billing.receipt': 'Receipt',
    'billing.placeholder_search': 'Search invoices...',
    'billing.filter_title': 'Filter Invoices',
    'features.fast_title': 'Lightning-fast processing',
    'features.fast_desc': 'Our infrastructure processes millions of transactions per second with 99.999% uptime. Say goodbye to delayed webhooks and slow API responses.',
    'features.latency': '< 50ms average latency',
    'features.idempotent': 'Idempotent API requests',
    'features.retries': 'Automatic webhook retries',
    'features.security_title': 'Bank-grade Security',
    'features.security_desc': 'Enterprise-level security built-in. We protect your data with AES-256 encryption and strict access controls.',
    'features.global_title': 'Global Reach',
    'features.global_desc': 'Accept payments from anywhere in the world. We support 135+ currencies and local payment methods out of the box.',
    'features.workflow_title': 'Automated Workflows',
    'features.workflow_desc': 'Connect Moneta to your existing tools. Trigger actions in your CRM, accounting software, or Slack based on real-time financial events.',
    'features.explore_integrations': 'Explore Integrations',
    'features.payment_received': 'Payment Received',
    'features.update_db': 'Update Database',
    'features.send_receipt': 'Send Receipt Email',
    'features.analytics_title': 'Advanced Analytics & Reporting',
    'features.analytics_desc': 'Get deep insights into your cashflow with customizable reports and dashboards. Track revenue, monitor churn, and forecast future growth with our AI-powered analytics engine.',
    'features.realtime_dashboards': 'Real-time Dashboards',
    'features.realtime_dashboards_desc': 'Monitor your business health in real-time.',
    'features.custom_reports': 'Custom Reports',
    'features.custom_reports_desc': 'Export data in CSV, PDF, or connect directly to your BI tools.',
    'features.api_title': 'Developer-first API',
    'features.api_desc': 'Built by developers, for developers. Our RESTful API is intuitive, well-documented, and designed to get you up and running in minutes, not days.',
    'features.cta_title': 'Ready to transform your financial operations?',
    'features.cta_desc': 'Join thousands of businesses that trust Moneta to power their payments and workflows.',
    'features.create_account': 'Create your free account',
    'blog.title': 'Our Blog',
    'blog.read_more': 'Read more',
    'blog.read_time': 'min read',
    'blog.post1_title': 'The Future of Financial Automation in 2024',
    'blog.post1_excerpt': 'Discover how AI and machine learning are revolutionizing the way businesses handle their daily financial operations.',
    'blog.post2_title': 'Best Practices for Webhook Security',
    'blog.post2_excerpt': 'Learn how to secure your webhook endpoints against common vulnerabilities and ensure data integrity.',
    'blog.post3_title': 'Scaling Your Payment Infrastructure',
    'blog.post3_excerpt': 'A comprehensive guide to building a payment system that can handle millions of transactions per day.',
    'blog.post4_title': 'Introducing Moneta API v2',
    'blog.post4_excerpt': 'We are excited to announce the next generation of our API, featuring improved performance and new capabilities.',
    'blog.post5_title': 'How to Reconcile Accounts Faster',
    'blog.post5_excerpt': 'Stop wasting hours on manual reconciliation. Here are 5 tips to automate your accounting workflows.',
    'blog.post6_title': 'Understanding Payment Gateways',
    'blog.post6_excerpt': 'A beginner-friendly breakdown of how payment gateways work behind the scenes.',
    'pricing.title': 'Pricing Plans',
    'pricing.popular': 'Most Popular',
    'pricing.month': 'month',
    'pricing.included': "What's included:",
    'pricing.faq_title': 'Frequently Asked Questions',
    'pricing.faq1_q': 'Can I switch plans later?',
    'pricing.faq1_a': 'Absolutely! You can upgrade or downgrade your plan at any time from your dashboard. Changes will be prorated.',
    'pricing.faq2_q': 'What payment methods do you accept?',
    'pricing.faq2_a': 'We accept all major credit cards (Visa, Mastercard, American Express) as well as PayPal and bank transfers for annual plans.',
    'pricing.faq3_q': 'Is there a long-term contract?',
    'pricing.faq3_a': 'No, all our plans are month-to-month unless you choose an annual subscription. You can cancel anytime without penalty.',
    'pricing.feature_api_1k': 'Up to 1,000 API calls/month',
    'pricing.feature_api_10k': 'Up to 10,000 API calls/month',
    'pricing.feature_api_unlimited': 'Unlimited API calls',
    'pricing.feature_analytics_basic': 'Basic analytics',
    'pricing.feature_analytics_adv': 'Advanced analytics & reporting',
    'pricing.feature_analytics_custom': 'Custom reporting',
    'pricing.feature_support_comm': 'Community support',
    'pricing.feature_support_email': 'Priority email support',
    'pricing.feature_support_247': '24/7 Phone & Email support',
    'pricing.feature_bank_1': '1 Bank account link',
    'pricing.feature_bank_unlimited': 'Unlimited bank accounts',
    'pricing.feature_webhook_std': 'Standard webhooks',
    'pricing.feature_webhook_custom': 'Custom webhook retries',
    'pricing.feature_team_5': 'Team collaboration (up to 5)',
    'pricing.feature_team_unlimited': 'Unlimited team members',
    'pricing.feature_manager': 'Dedicated account manager',
    'pricing.feature_sla': 'SLA guarantee',
    'pricing.feature_integrations': 'Custom integrations',
    'pricing.starter_name': 'Starter',
    'pricing.starter_desc': 'Perfect for individuals and small projects just getting started.',
    'pricing.pro_name': 'Pro',
    'pricing.pro_desc': 'Ideal for growing businesses needing more power and flexibility.',
    'pricing.enterprise_name': 'Enterprise',
    'pricing.enterprise_desc': 'For large scale organizations requiring custom solutions.',
    'partners.title': 'Our Partners Trust with Us',
    'finance.title': 'Smarter Finance Better Decisions',
    'finance.desc': "Moneta is a modern finance app built to help young users manage money smarter. Inspired by the 50/30/20 rule, Moneta's onboarding protocol, it offers simple tools to track spending, save efficiently, and make better financial decisions — all in one clean, intuitive interface.",
    'finance.monthly_overview': 'Monthly Overview',
    'features.title': 'What Moneta Can Do for You?',
    'features.spending_alerts_title': 'Smart Spending Alerts',
    'features.spending_alerts_desc': 'Get real-time notifications every time you spend, so you always stay in control of your budget.',
    'features.tracker_title': 'Balance & Expense Tracker',
    'features.tracker_desc': 'Get real-time notifications every time you spend, so you always stay in control of your budget.',
    'features.explore_more': 'Explore More',
    'features.spent_at': 'You spent',
    'features.received_from': 'You received',
    'features.at': 'at',
    'features.from': 'from',
    'common.today': 'Today',
    'newsletter.title': 'Keep Up with the News Latest',
    'newsletter.subtitle': 'Subscribe to our newsletter to get the latest info and features.',
    'newsletter.placeholder': 'Enter your email',
    'newsletter.subscribe': 'Subscribe',
    'footer.description': 'Simplify your digital money payments with Moneta. Fast, secure, and easy to use.',
    'footer.follow': 'Follow',
    'footer.links': 'Links',
    'footer.benefits': 'Benefits',
    'footer.support': 'Support',
    'footer.security': 'Security',
    'footer.analytics': 'Analytics',
    'footer.savings': 'Savings',
    'footer.rewards': 'Rewards',
    'footer.help_center': 'Help Center',
    'footer.contact_us': 'Contact Us',
    'footer.privacy': 'Privacy',
    'footer.terms': 'Terms',
    'footer.rights': 'All rights reserved.',
    
    // Admin Panel
    'admin.title': 'Admin Panel',
    'admin.dashboard': 'Dashboard',
    'admin.users': 'Users',
    'admin.packages': 'Packages',
    'admin.banks': 'Banks',
    'admin.durations': 'Durations',
    'admin.userPackages': 'User Packages',
    'admin.webhooks': 'Webhooks',
    'admin.transactions': 'Transactions',
    'admin.settings': 'Settings',
    'admin.backToDashboard': 'Back to Dashboard',
    
    // Admin Stats
    'admin.stats.totalUsers': 'Total Users',
    'admin.stats.activePackages': 'Active Packages',
    'admin.stats.totalTransactions': 'Total Transactions',
    'admin.stats.activeWebhooks': 'Active Webhooks',
    'admin.stats.recentUsers': 'Recent Users',
    'admin.stats.recentTransactions': 'Recent Transactions',
    
    // Admin Users
    'admin.users.title': 'User Management',
    'admin.users.email': 'Email',
    'admin.users.fullName': 'Full Name',
    'admin.users.role': 'Role',
    'admin.users.createdAt': 'Created At',
    'admin.users.updateRole': 'Update Role',
    'admin.users.roleUpdated': 'Role updated successfully',
    'admin.users.searchPlaceholder': 'Search by email or name...',
    
    // Admin Packages
    'admin.packages.title': 'Package Management',
    'admin.packages.createPackage': 'Create Package',
    'admin.packages.editPackage': 'Edit Package',
    'admin.packages.name': 'Package Name',
    'admin.packages.status': 'Status',
    'admin.packages.price': 'Price (VND)',
    'admin.packages.maxTransactions': 'Max Transactions',
    'admin.packages.maxWebhooks': 'Max Webhooks',
    'admin.packages.banks': 'Banks',
    'admin.packages.pricing': 'Pricing',
    'admin.packages.packageCreated': 'Package created successfully',
    'admin.packages.packageUpdated': 'Package updated successfully',
    
    // Admin Banks
    'admin.banks.title': 'Bank Management',
    'admin.banks.createBank': 'Add Bank',
    'admin.banks.editBank': 'Edit Bank',
    'admin.banks.name': 'Bank Name',
    'admin.banks.code': 'Bank Code',
    'admin.banks.iconUrl': 'Icon URL',
    'admin.banks.bankCreated': 'Bank added successfully',
    'admin.banks.bankUpdated': 'Bank updated successfully',
    
    // Admin Actions
    'admin.actions.create': 'Create',
    'admin.actions.edit': 'Edit',
    'admin.actions.delete': 'Delete',
    'admin.actions.save': 'Save',
    'admin.actions.cancel': 'Cancel',
    'admin.actions.search': 'Search',
    'admin.actions.filter': 'Filter',
    'admin.actions.export': 'Export',
    'admin.actions.refresh': 'Refresh',
  },
  vi: {
    'nav.home': 'Trang chủ',
    'nav.features': 'Tính năng',
    'nav.pricing': 'Bảng giá',
    'nav.docs': 'Tài liệu',
    'nav.blog': 'Blog',
    'nav.login': 'Đăng nhập',
    'nav.signup': 'Đăng ký',
    'nav.overview': 'Tổng quan',
    'nav.bank': 'Ngân hàng',
    'nav.webhook': 'Webhook',
    'nav.billing': 'Thanh toán',
    'nav.support': 'Hỗ trợ',
    'nav.admin': 'Bảng Quản Trị',
    'hero.title': 'Tài chính hiện đại cho mọi người',
    'hero.subtitle': 'Moneta giúp bạn quản lý tiền bạc, theo dõi chi tiêu và phát triển tài sản một cách dễ dàng.',
    'hero.cta': 'Bắt đầu ngay',
    'hero.users_active': 'Người dùng hoạt động',
    'hero.countries': 'Quốc gia',
    'hero.finance_app': 'Ứng dụng tài chính',
    'hero.cardholder': 'Chủ thẻ',
    'dashboard.welcome': 'Chào mừng',
    'dashboard.balance': 'Số dư của tôi',
    'dashboard.spent': 'Chi tiêu hàng tháng',
    'dashboard.income': 'Thu nhập hàng tháng',
    'dashboard.compared': 'So với tháng trước',
    'dashboard.transfer': 'Chuyển tiền',
    'dashboard.received': 'Nhận tiền',
    'dashboard.cashflow': 'Dòng tiền',
    'dashboard.recent_activity': 'Hoạt động gần đây',
    'dashboard.expense': 'Chi phí',
    'dashboard.this_week': 'Tuần này',
    'dashboard.this_month': 'Tháng này',
    'dashboard.this_year': 'Năm nay',
    'dashboard.today': 'Hôm nay',
    'dashboard.notifications': 'Thông báo',
    'dashboard.mark_read': 'Đánh dấu đã đọc',
    'dashboard.view_all': 'Xem tất cả',
    'common.search': 'Tìm kiếm',
    'common.filter': 'Bộ lọc',
    'common.columns': 'Cột hiển thị',
    'common.save': 'Lưu thay đổi',
    'common.cancel': 'Hủy',
    'common.confirm': 'Xác nhận',
    'common.actions': 'Hành động',
    'common.status': 'Trạng thái',
    'common.date': 'Ngày',
    'common.amount': 'Số tiền',
    'common.loading': 'Đang tải...',
    'common.edit': 'Sửa',
    'common.delete': 'Xóa',
    'common.create': 'Tạo mới',
    'common.back': 'Quay lại',
    'common.copy': 'Sao chép',
    'auth.login_title': 'Chào mừng trở lại',
    'auth.login_subtitle': 'Nhập thông tin để truy cập tài khoản của bạn',
    'auth.register_title': 'Tạo tài khoản',
    'auth.register_subtitle': 'Tham gia Moneta và bắt đầu quản lý tài chính',
    'auth.register_success': 'Đăng ký thành công! Vui lòng xác thực email.',
    'auth.register_failed': 'Đăng ký thất bại',
    'auth.login_success': 'Đăng nhập thành công!',
    'auth.login_failed': 'Đăng nhập thất bại',
    'auth.verification_success': 'Xác thực thành công!',
    'auth.email_verified': 'Email đã được xác thực thành công!',
    'auth.code_sent': 'Mã xác thực đã được gửi đến email của bạn',
    'auth.code_resent': 'Mã xác thực đã được gửi lại thành công',
    'auth.verify_email_required': 'Vui lòng xác thực email để tiếp tục',
    'auth.verify_login_required': 'Vui lòng xác thực đăng nhập từ thiết bị mới',
    'auth.forgot_password': 'Quên mật khẩu?',
    'auth.forgot_password_desc': 'Nhập địa chỉ email của bạn và chúng tôi sẽ gửi hướng dẫn đặt lại mật khẩu.',
    'auth.send_reset_link': 'Gửi liên kết đặt lại',
    'auth.back_to_login': 'Quay lại đăng nhập',
    'auth.no_account': 'Chưa có tài khoản?',
    'auth.have_account': 'Đã có tài khoản?',
    'auth.email': 'Địa chỉ Email',
    'auth.password': 'Mật khẩu',
    'auth.full_name': 'Họ và tên',
    'auth.verify_title': 'Xác thực tài khoản',
    'auth.verify_desc': 'Chúng tôi đã gửi mã OTP gồm 6 chữ số đến email của bạn. Vui lòng nhập mã để tiếp tục.',
    'auth.verify_email_title': 'Xác thực Email',
    'auth.verify_email_desc': 'Chúng tôi đã gửi mã 6 chữ số đến email của bạn. Vui lòng nhập mã bên dưới.',
    'auth.verify_login_title': 'Xác thực đăng nhập',
    'auth.verify_login_desc': 'Chúng tôi phát hiện đăng nhập từ thiết bị mới. Vui lòng nhập mã 6 chữ số đã gửi đến email của bạn.',
    'auth.verify_2fa_title': 'Xác thực 2 yếu tố',
    'auth.verify_2fa_desc': 'Nhập mã 6 chữ số từ ứng dụng xác thực của bạn.',
    'auth.resend': 'Gửi lại mã',
    'auth.resend_after': 'Gửi lại mã sau',
    'auth.back_to_register': 'Quay lại đăng ký',
    'auth.logout': 'Đăng xuất',
    'auth.passwords_do_not_match': 'Mật khẩu không khớp',
    'profile.title': 'Thông tin người dùng',
    'profile.settings': 'Cài đặt',
    'profile.personal': 'Thông tin cá nhân',
    'profile.notifications': 'Cài đặt thông báo',
    'profile.security': 'Cài đặt bảo mật',
    'profile.linked': 'Liên kết tài khoản',
    'profile.your_profile': 'Hồ sơ của bạn',
    'profile.phone': 'Số điện thoại',
    'profile.change_password': 'Đổi mật khẩu',
    'profile.current_password': 'Mật khẩu hiện tại',
    'profile.new_password': 'Mật khẩu mới',
    'profile.confirm_new_password': 'Xác nhận mật khẩu mới',
    'profile.update_password': 'Cập nhật mật khẩu',
    'profile.email_notifs': 'Thông báo qua email',
    'profile.email_notifs_desc': 'Các cập nhật tự động gửi tới email chính của bạn.',
    'profile.settings_updated': 'Cài đặt đã được cập nhật thành công!',
    'profile.profile_updated': 'Hồ sơ đã được cập nhật thành công!',
    'profile.password_changed': 'Mật khẩu đã được thay đổi thành công!',
    'profile.device_removed': 'Thiết bị đã được xóa thành công!',
    'profile.notif_success_title': 'Thanh toán thành công',
    'profile.notif_success_desc': 'Nhận email cho mỗi giao dịch thanh toán thành công.',
    'profile.notif_failed_title': 'Thanh toán thất bại',
    'profile.notif_failed_desc': 'Được thông báo ngay khi một lần thanh toán bị lỗi.',
    'profile.notif_dispute_title': 'Tranh chấp',
    'profile.notif_dispute_desc': 'Nhận cảnh báo khi có tranh chấp mới và hạn chót cung cấp bằng chứng.',
    'profile.notif_payout_title': 'Chi tiền',
    'profile.notif_payout_desc': 'Nhận thông báo khi tiền được chuyển tới tài khoản ngân hàng của bạn.',
    'profile.notif_member_title': 'Thành viên mới',
    'profile.notif_member_desc': 'Nhận xác nhận khi có thành viên mới tham gia nhóm.',
    'profile.login_alerts': 'Cảnh báo đăng nhập',
    'profile.login_alerts_desc': 'Nhận thông báo khi có đăng nhập từ thiết bị hoặc vị trí mới.',
    'profile.trusted_devices': 'Các thiết bị tin cậy',
    'profile.login_history': 'Lịch sử đăng nhập',
    'profile.device': 'Thiết bị',
    'profile.last_active': 'Hoạt động lần cuối',
    'profile.remove_device': 'Gỡ bỏ thiết bị',
    'profile.remove_device_confirm': 'Bạn có chắc chắn muốn gỡ bỏ thiết bị này khỏi danh sách tin cậy?',
    'profile.ip_address': 'Địa chỉ IP',
    'profile.location': 'Vị trí',
    'profile.login_success': 'Thành công',
    'profile.login_failed': 'Thất bại',
    'profile.social_login': 'Đăng nhập mạng xã hội',
    'profile.social_login_desc': 'Liên kết tài khoản mạng xã hội để đăng nhập nhanh hơn.',
    'profile.activity_notifs': 'Thông báo biến động',
    'profile.activity_notifs_desc': 'Nhận thông báo qua các ứng dụng nhắn tin.',
    'profile.linked_status': 'Đã liên kết',
    'profile.not_linked_status': 'Chưa liên kết',
    'profile.unlink': 'Hủy liên kết',
    'profile.link_now': 'Liên kết ngay',
    'profile.verify_email': 'Xác thực Email',
    'profile.verify_email_desc': 'Vui lòng xác thực địa chỉ email để truy cập đầy đủ tính năng.',
    'profile.send_verification_code': 'Gửi mã xác thực',
    'profile.verify_email_modal_desc': 'Nhập mã 6 chữ số đã gửi đến email để xác thực tài khoản.',
    'common.please_fill_all_fields': 'Vui lòng điền đầy đủ thông tin',
    'common.done': 'Hoàn tất',
    'common.coming_soon': 'Sắp ra mắt',
    '2fa.title': 'Cấu hình xác thực 2 yếu tố',
    '2fa.enabled': 'Đã bật 2FA thành công!',
    '2fa.disabled': 'Đã tắt 2FA thành công!',
    '2fa.step1_title': 'Quét mã QR',
    '2fa.step1_desc': 'Sử dụng ứng dụng xác thực để quét mã QR bên dưới.',
    '2fa.step2_title': 'Nhập mã xác nhận',
    '2fa.step2_desc': 'Nhập mã 6 chữ số từ ứng dụng của bạn để hoàn tất cài đặt.',
    '2fa.manual_entry': 'Hoặc nhập mã thủ công',
    '2fa.next': 'Tiếp theo',
    '2fa.back': 'Quay lại',
    '2fa.complete': 'Hoàn tất',
    'webhook.edit_title': 'Chỉnh sửa webhook endpoint',
    'webhook.create_title': 'Tạo webhook endpoint',
    'webhook.enabled': 'Đang bật',
    'webhook.endpoint_desc': 'Endpoint phải chấp nhận request POST với body JSON. URL chỉ dùng GET (ví dụ /me) sẽ trả 404 khi gửi webhook.',
    'webhook.signing_secret': 'Signing secret',
    'webhook.signing_secret_desc': 'Dùng secret này để xác minh sự kiện webhook thực sự được gửi từ HyperPay.',
    'webhook.linked_bank': 'Tài khoản ngân hàng liên kết',
    'webhook.no_bank_found': 'Không tìm thấy tài khoản ngân hàng. Hãy thêm tài khoản ở trang Banking trước.',
    'webhook.linked_bank_desc': 'Nếu không chọn tài khoản nào, webhook sẽ nhận sự kiện từ mọi tài khoản hợp lệ.',
    'webhook.direction': 'Hướng giao dịch',
    'webhook.direction_both': 'Cả hai',
    'webhook.direction_in': 'Tiền vào',
    'webhook.direction_out': 'Tiền ra',
    'webhook.content_type': 'Loại nội dung',
    'webhook.retry_desc': 'Retry khi response khác 2xx',
    'webhook.max_retries': 'Số lần retry tối đa',
    'webhook.auth': 'Xác thực',
    'webhook.auth_type': 'Loại xác thực',
    'webhook.auth_none': 'Không',
    'webhook.auth_basic': 'Basic Auth',
    'webhook.auth_bearer': 'Bearer Token',
    'webhook.payment_code_rules': 'Luật mã thanh toán',
    'webhook.require_payment_code': 'Yêu cầu có mã thanh toán',
    'webhook.enable_extraction': 'Bật luật trích xuất mã thanh toán',
    'webhook.enable_endpoint': 'Bật endpoint này',
    'webhook.save': 'Lưu cấu hình',
    'docs.title': 'Tài liệu API',
    'docs.getting_started': 'Bắt đầu',
    'docs.introduction': 'Giới thiệu',
    'docs.authentication': 'Xác thực',
    'docs.payments_api': 'API thanh toán',
    'docs.create_payment': 'Tạo thanh toán',
    'docs.retrieve_payment': 'Lấy thông tin thanh toán',
    'docs.webhooks': 'Webhooks',
    'docs.handling_webhooks': 'Xử lý Webhooks',
    'docs.intro_desc': 'Chào mừng bạn đến với Moneta API. Bạn có thể sử dụng API của chúng tôi để truy cập các điểm cuối Moneta API, lấy thông tin về các thành phần cơ sở dữ liệu khác nhau, tạo thanh toán mới và quản lý an toàn các hoạt động tài chính của bạn.',
    'docs.base_url': 'URL cơ sở:',
    'docs.base_url_desc': 'Tất cả các yêu cầu API phải được gửi tới URL cơ sở {url}.',
    'docs.auth_desc1': 'Moneta API sử dụng các khóa API để xác thực các yêu cầu. Bạn có thể xem và quản lý các khóa API của mình trong Bảng điều khiển Moneta.',
    'docs.auth_desc2': 'Xác thực với API được thực hiện thông qua HTTP Bearer Auth. Cung cấp khóa API của bạn làm giá trị mã thông báo bearer.',
    'docs.create_payment_desc': 'Tạo một đối tượng thanh toán mới. Đây là bước đầu tiên trong quy trình thanh toán.',
    'docs.endpoint': 'Điểm cuối',
    'docs.parameters': 'Tham số',
    'docs.param_amount_desc': 'Một số nguyên dương đại diện cho số tiền cần tính phí theo đơn vị tiền tệ nhỏ nhất (ví dụ: 100 cent để tính phí 1,00 đô la).',
    'docs.param_currency_desc': 'Mã tiền tệ ISO ba chữ số, viết thường. Phải là loại tiền tệ được hỗ trợ.',
    'docs.example_request': 'Yêu cầu ví dụ',
    'docs.example_response': 'Phản hồi ví dụ',
    'docs.webhooks_desc': 'Moneta sử dụng webhooks để thông báo cho ứng dụng của bạn khi có sự kiện xảy ra trong tài khoản của bạn. Webhooks đặc biệt hữu ích cho các sự kiện không đồng bộ như khi ngân hàng của khách hàng xác nhận thanh toán.',
    'docs.verifying_signatures': 'Xác minh chữ ký',
    'docs.verifying_signatures_desc': 'Chúng tôi thực sự khuyên bạn nên xác minh chữ ký webhook để đảm bảo rằng các sự kiện được gửi bởi Moneta, không phải bởi bên thứ ba.',
    'blog.back': 'Quay lại Blog',
    'blog.author_role': 'CEO & Người sáng lập',
    'blog.tags': 'Thẻ',
    'blog.share': 'Chia sẻ',
    'blog.landscape_title': 'Bối cảnh hiện tại',
    'blog.looking_ahead': 'Nhìn về phía trước',
    'blog.quote': '"Tương lai của tài chính không chỉ là chuyển tiền nhanh hơn, mà là làm cho tiền thông minh hơn."',
    'support.title': 'Phiếu hỗ trợ',
    'support.placeholder_search': 'Tìm kiếm phiếu...',
    'support.filter_title': 'Bộ lọc phiếu',
    'support.add': 'Tạo phiếu',
    'support.edit': 'Sửa phiếu',
    'support.ticket_id': 'Mã phiếu',
    'support.subject': 'Chủ đề',
    'support.priority': 'Độ ưu tiên',
    'support.created_at': 'Ngày tạo',
    'support.category': 'Danh mục',
    'support.description': 'Mô tả',
    'support.placeholder_subject': 'Mô tả ngắn gọn về vấn đề',
    'support.placeholder_category': 'Chọn một danh mục...',
    'support.placeholder_description': 'Vui lòng cung cấp càng nhiều chi tiết càng tốt...',
    'support.submit': 'Gửi phiếu',
    'support.status_open': 'Mở',
    'support.status_in_progress': 'Đang xử lý',
    'support.status_closed': 'Đã đóng',
    'support.priority_high': 'Cao',
    'support.priority_medium': 'Trung bình',
    'support.priority_low': 'Thấp',
    'support.cat_billing': 'Thanh toán',
    'support.cat_technical': 'Vấn đề kỹ thuật',
    'support.cat_account': 'Quản lý tài khoản',
    'support.cat_other': 'Khác',
    'verify_otp.title': 'Xác minh tài khoản của bạn',
    'verify_otp.desc': 'Chúng tôi đã gửi mã xác minh gồm 6 chữ số đến email của bạn. Vui lòng nhập mã đó bên dưới để tiếp tục.',
    'verify_otp.placeholder': 'Nhập mã 6 chữ số',
    'verify_otp.verify': 'Xác minh tài khoản',
    'verify_otp.resend_prompt': 'Không nhận được mã?',
    'verify_otp.resend_button': 'Gửi lại mã',
    'verify_otp.resend_wait': 'Gửi lại sau',
    'verify_otp.back_to_login': 'Quay lại đăng nhập',
    'bank.title': 'Tài khoản ngân hàng',
    'bank.add': 'Thêm ngân hàng',
    'bank.edit': 'Chỉnh sửa tài khoản',
    'bank.name': 'Tên ngân hàng',
    'bank.account_no': 'Số tài khoản',
    'bank.type': 'Loại',
    'bank.select': 'Chọn ngân hàng',
    'bank.placeholder_search': 'Tìm kiếm tài khoản...',
    'bank.filter_title': 'Bộ lọc tài khoản',
    'bank.all_banks': 'Tất cả ngân hàng',
    'bank.creation_time': 'Thời gian tạo',
    'bank.all_statuses': 'Tất cả trạng thái',
    'bank.active': 'Hoạt động',
    'bank.inactive': 'Ngưng hoạt động',
    'bank.all_types': 'Tất cả loại',
    'bank.personal': 'Cá nhân',
    'bank.business': 'Doanh nghiệp',
    'bank.apply_filters': 'Áp dụng bộ lọc',
    'bank.reset': 'Đặt lại',
    'bank.password': 'Mật khẩu',
    'bank.password_placeholder': 'Nhập mật khẩu',
    'bank.password_edit_placeholder': 'Để trống nếu không muốn đổi',
    'webhook.title': 'Webhooks',
    'webhook.list': 'Danh sách Webhook',
    'webhook.logs': 'Nhật ký sự kiện',
    'webhook.add': 'Thêm Webhook',
    'webhook.endpoint_url': 'URL điểm cuối',
    'webhook.events': 'Sự kiện',
    'webhook.placeholder_search': 'Tìm kiếm webhook...',
    'webhook.placeholder_search_logs': 'Tìm kiếm nhật ký...',
    'webhook.filter_title': 'Bộ lọc Webhook',
    'webhook.event': 'Sự kiện',
    'billing.title': 'Thanh toán & Gói cước',
    'billing.current_plan': 'Gói hiện tại',
    'billing.pro_plan': 'Gói Pro',
    'billing.billed_monthly': 'Thanh toán hàng tháng. Lần tới vào 1 thg 6, 2024.',
    'billing.upgrade': 'Nâng cấp',
    'billing.cancel': 'Hủy bỏ',
    'billing.available_balance': 'Số dư khả dụng',
    'billing.auto_recharge': 'Tự động nạp tiền',
    'billing.enabled_below': 'Đã bật (dưới $50)',
    'billing.payment_method': 'Phương thức thanh toán',
    'billing.add_funds': 'Nạp tiền',
    'billing.api_usage': 'Sử dụng API',
    'billing.calls_limit': 'lượt gọi trong 30 ngày qua',
    'billing.purchase_history': 'Lịch sử thanh toán',
    'billing.invoice_id': 'Mã hóa đơn',
    'billing.plan_item': 'Gói / Mục',
    'billing.amount': 'Số tiền',
    'billing.receipt': 'Biên lai',
    'billing.placeholder_search': 'Tìm kiếm hóa đơn...',
    'billing.filter_title': 'Bộ lọc hóa đơn',
    'features.fast_title': 'Xử lý nhanh như chớp',
    'features.fast_desc': 'Cơ sở hạ tầng của chúng tôi xử lý hàng triệu giao dịch mỗi giây với thời gian hoạt động 99,999%. Nói lời tạm biệt với các webhook bị trì hoãn và phản hồi API chậm.',
    'features.latency': 'Độ trễ trung bình < 50ms',
    'features.idempotent': 'Yêu cầu API lũy đẳng',
    'features.retries': 'Tự động thử lại webhook',
    'features.security_title': 'Bảo mật cấp ngân hàng',
    'features.security_desc': 'Bảo mật cấp doanh nghiệp được tích hợp sẵn. Chúng tôi bảo vệ dữ liệu của bạn bằng mã hóa AES-256 và kiểm soát truy cập nghiêm ngặt.',
    'features.global_title': 'Phạm vi toàn cầu',
    'features.global_desc': 'Chấp nhận thanh toán từ mọi nơi trên thế giới. Chúng tôi hỗ trợ hơn 135 loại tiền tệ và các phương thức thanh toán địa phương ngay khi xuất xưởng.',
    'features.workflow_title': 'Quy trình làm việc tự động',
    'features.workflow_desc': 'Kết nối Moneta với các công cụ hiện có của bạn. Kích hoạt các hành động trong CRM, phần mềm kế toán hoặc Slack dựa trên các sự kiện tài chính thời gian thực.',
    'features.explore_integrations': 'Khám phá các tích hợp',
    'features.payment_received': 'Đã nhận thanh toán',
    'features.update_db': 'Cập nhật cơ sở dữ liệu',
    'features.send_receipt': 'Gửi email biên lai',
    'features.analytics_title': 'Phân tích & Báo cáo nâng cao',
    'features.analytics_desc': 'Nhận thông tin chi tiết sâu sắc về dòng tiền của bạn với các báo cáo và bảng điều khiển có thể tùy chỉnh. Theo dõi doanh thu, giám sát tỷ lệ rời bỏ và dự báo tăng trưởng trong tương lai với công cụ phân tích hỗ trợ AI của chúng tôi.',
    'features.realtime_dashboards': 'Bảng điều khiển thời gian thực',
    'features.realtime_dashboards_desc': 'Theo dõi sức khỏe doanh nghiệp của bạn trong thời gian thực.',
    'features.custom_reports': 'Báo cáo tùy chỉnh',
    'features.custom_reports_desc': 'Xuất dữ liệu ở định dạng CSV, PDF hoặc kết nối trực tiếp với các công cụ BI của bạn.',
    'features.api_title': 'API ưu tiên cho nhà phát triển',
    'features.api_desc': 'Được xây dựng bởi các nhà phát triển, dành cho các nhà phát triển. API RESTful của chúng tôi trực quan, được tài liệu hóa tốt và được thiết kế để giúp bạn bắt đầu và chạy trong vài phút, không phải vài ngày.',
    'features.cta_title': 'Sẵn sàng chuyển đổi hoạt động tài chính của bạn?',
    'features.cta_desc': 'Tham gia cùng hàng ngàn doanh nghiệp tin tưởng Moneta để cung cấp năng lượng cho các khoản thanh toán và quy trình làm việc của họ.',
    'features.create_account': 'Tạo tài khoản miễn phí của bạn',
    'blog.title': 'Blog của chúng tôi',
    'blog.read_more': 'Đọc thêm',
    'blog.read_time': 'phút đọc',
    'blog.post1_title': 'Tương lai của tự động hóa tài chính vào năm 2024',
    'blog.post1_excerpt': 'Khám phá cách AI và học máy đang cách mạng hóa cách các doanh nghiệp xử lý các hoạt động tài chính hàng ngày của họ.',
    'blog.post2_title': 'Các phương pháp hay nhất cho bảo mật Webhook',
    'blog.post2_excerpt': 'Tìm hiểu cách bảo mật các điểm cuối webhook của bạn chống lại các lỗ hổng phổ biến và đảm bảo tính toàn vẹn của dữ liệu.',
    'blog.post3_title': 'Mở rộng cơ sở hạ tầng thanh toán của bạn',
    'blog.post3_excerpt': 'Hướng dẫn toàn diện để xây dựng hệ thống thanh toán có thể xử lý hàng triệu giao dịch mỗi ngày.',
    'blog.post4_title': 'Giới thiệu Moneta API v2',
    'blog.post4_excerpt': 'Chúng tôi rất vui mừng thông báo thế hệ API tiếp theo của mình, với hiệu suất được cải thiện và các khả năng mới.',
    'blog.post5_title': 'Cách đối soát tài khoản nhanh hơn',
    'blog.post5_excerpt': 'Ngừng lãng phí hàng giờ vào việc đối soát thủ công. Dưới đây là 5 mẹo để tự động hóa quy trình kế toán của bạn.',
    'blog.post6_title': 'Hiểu về cổng thanh toán',
    'blog.post6_excerpt': 'Một phân tích thân thiện với người mới bắt đầu về cách các cổng thanh toán hoạt động đằng sau hậu trường.',
    'pricing.title': 'Bảng giá',
    'pricing.popular': 'Phổ biến nhất',
    'pricing.month': 'tháng',
    'pricing.included': 'Bao gồm:',
    'pricing.faq_title': 'Câu hỏi thường gặp',
    'pricing.faq1_q': 'Tôi có thể đổi gói sau không?',
    'pricing.faq1_a': 'Chắc chắn rồi! Bạn có thể nâng cấp hoặc hạ cấp gói của mình bất kỳ lúc nào từ bảng điều khiển. Các thay đổi sẽ được tính theo tỷ lệ.',
    'pricing.faq2_q': 'Bạn chấp nhận phương thức thanh toán nào?',
    'pricing.faq2_a': 'Chúng tôi chấp nhận tất cả các loại thẻ tín dụng chính (Visa, Mastercard, American Express) cũng như PayPal và chuyển khoản ngân hàng cho các gói hàng năm.',
    'pricing.faq3_q': 'Có hợp đồng dài hạn không?',
    'pricing.faq3_a': 'Không, tất cả các gói của chúng tôi là hàng tháng trừ khi bạn chọn đăng ký hàng năm. Bạn có thể hủy bất kỳ lúc nào mà không bị phạt.',
    'pricing.feature_api_1k': 'Lên đến 1.000 cuộc gọi API/tháng',
    'pricing.feature_api_10k': 'Lên đến 10.000 cuộc gọi API/tháng',
    'pricing.feature_api_unlimited': 'Không giới hạn cuộc gọi API',
    'pricing.feature_analytics_basic': 'Phân tích cơ bản',
    'pricing.feature_analytics_adv': 'Phân tích & báo cáo nâng cao',
    'pricing.feature_analytics_custom': 'Báo cáo tùy chỉnh',
    'pricing.feature_support_comm': 'Hỗ trợ cộng đồng',
    'pricing.feature_support_email': 'Hỗ trợ email ưu tiên',
    'pricing.feature_support_247': 'Hỗ trợ điện thoại & email 24/7',
    'pricing.feature_bank_1': 'Liên kết 1 tài khoản ngân hàng',
    'pricing.feature_bank_unlimited': 'Không giới hạn tài khoản ngân hàng',
    'pricing.feature_webhook_std': 'Webhook tiêu chuẩn',
    'pricing.feature_webhook_custom': 'Thử lại webhook tùy chỉnh',
    'pricing.feature_team_5': 'Cộng tác nhóm (lên đến 5 người)',
    'pricing.feature_team_unlimited': 'Không giới hạn thành viên nhóm',
    'pricing.feature_manager': 'Quản lý tài khoản riêng',
    'pricing.feature_sla': 'Đảm bảo SLA',
    'pricing.feature_integrations': 'Tích hợp tùy chỉnh',
    'pricing.starter_name': 'Cơ bản',
    'pricing.starter_desc': 'Hoàn hảo cho cá nhân và các dự án nhỏ mới bắt đầu.',
    'pricing.pro_name': 'Chuyên nghiệp',
    'pricing.pro_desc': 'Lý tưởng cho các doanh nghiệp đang phát triển cần nhiều sức mạnh và sự linh hoạt hơn.',
    'pricing.enterprise_name': 'Doanh nghiệp',
    'pricing.enterprise_desc': 'Dành cho các tổ chức quy mô lớn yêu cầu các giải pháp tùy chỉnh.',
    'partners.title': 'Các đối tác tin tưởng chúng tôi',
    'finance.title': 'Tài chính thông minh hơn Quyết định tốt hơn',
    'finance.desc': 'Moneta là một ứng dụng tài chính hiện đại được xây dựng để giúp người dùng trẻ quản lý tiền thông minh hơn. Lấy cảm hứng từ quy tắc 50/30/20, giao thức giới thiệu của Moneta, nó cung cấp các công cụ đơn giản để theo dõi chi tiêu, tiết kiệm hiệu quả và đưa ra các quyết định tài chính tốt hơn — tất cả trong một giao diện sạch sẽ, trực quan.',
    'finance.monthly_overview': 'Tổng quan hàng tháng',
    'features.title': 'Moneta có thể làm gì cho bạn?',
    'features.spending_alerts_title': 'Cảnh báo chi tiêu thông minh',
    'features.spending_alerts_desc': 'Nhận thông báo theo thời gian thực mỗi khi bạn chi tiêu, để bạn luôn kiểm soát được ngân sách của mình.',
    'features.tracker_title': 'Theo dõi số dư & chi phí',
    'features.tracker_desc': 'Nhận thông báo theo thời gian thực mỗi khi bạn chi tiêu, để bạn luôn kiểm soát được ngân sách của mình.',
    'features.explore_more': 'Khám phá thêm',
    'features.spent_at': 'Bạn đã chi',
    'features.received_from': 'Bạn đã nhận',
    'features.at': 'tại',
    'features.from': 'từ',
    'common.today': 'Hôm nay',
    'newsletter.title': 'Cập nhật tin tức mới nhất',
    'newsletter.subtitle': 'Đăng ký nhận bản tin của chúng tôi để nhận thông tin và tính năng mới nhất.',
    'newsletter.placeholder': 'Nhập email của bạn',
    'newsletter.subscribe': 'Đăng ký',
    'footer.description': 'Đơn giản hóa việc thanh toán tiền kỹ thuật số của bạn với Moneta. Nhanh chóng, an toàn và dễ sử dụng.',
    'footer.follow': 'Theo dõi',
    'footer.links': 'Liên kết',
    'footer.benefits': 'Lợi ích',
    'footer.support': 'Hỗ trợ',
    'footer.security': 'Bảo mật',
    'footer.analytics': 'Phân tích',
    'footer.savings': 'Tiết kiệm',
    'footer.rewards': 'Phần thưởng',
    'footer.help_center': 'Trung tâm trợ giúp',
    'footer.contact_us': 'Liên hệ',
    'footer.privacy': 'Quyền riêng tư',
    'footer.terms': 'Điều khoản',
    'footer.rights': 'Bản quyền đã được bảo hộ.',
    
    // Admin Panel
    'admin.title': 'Bảng Quản Trị',
    'admin.dashboard': 'Tổng Quan',
    'admin.users': 'Người Dùng',
    'admin.packages': 'Gói Dịch Vụ',
    'admin.banks': 'Ngân Hàng',
    'admin.durations': 'Thời Hạn',
    'admin.userPackages': 'Gói Người Dùng',
    'admin.webhooks': 'Webhook',
    'admin.transactions': 'Giao Dịch',
    'admin.settings': 'Cài Đặt',
    'admin.backToDashboard': 'Quay Lại Dashboard',
    
    // Admin Stats
    'admin.stats.totalUsers': 'Tổng Người Dùng',
    'admin.stats.activePackages': 'Gói Đang Hoạt Động',
    'admin.stats.totalTransactions': 'Tổng Giao Dịch',
    'admin.stats.activeWebhooks': 'Webhook Hoạt Động',
    'admin.stats.recentUsers': 'Người Dùng Mới',
    'admin.stats.recentTransactions': 'Giao Dịch Gần Đây',
    
    // Admin Users
    'admin.users.title': 'Quản Lý Người Dùng',
    'admin.users.email': 'Email',
    'admin.users.fullName': 'Họ Tên',
    'admin.users.role': 'Vai Trò',
    'admin.users.createdAt': 'Ngày Tạo',
    'admin.users.updateRole': 'Cập Nhật Vai Trò',
    'admin.users.roleUpdated': 'Đã cập nhật vai trò thành công',
    'admin.users.searchPlaceholder': 'Tìm theo email hoặc tên...',
    
    // Admin Packages
    'admin.packages.title': 'Quản Lý Gói Dịch Vụ',
    'admin.packages.createPackage': 'Tạo Gói Mới',
    'admin.packages.editPackage': 'Chỉnh Sửa Gói',
    'admin.packages.name': 'Tên Gói',
    'admin.packages.status': 'Trạng Thái',
    'admin.packages.price': 'Giá (VNĐ)',
    'admin.packages.maxTransactions': 'Giới Hạn Giao Dịch',
    'admin.packages.maxWebhooks': 'Giới Hạn Webhook',
    'admin.packages.banks': 'Ngân Hàng',
    'admin.packages.pricing': 'Bảng Giá',
    'admin.packages.packageCreated': 'Đã tạo gói thành công',
    'admin.packages.packageUpdated': 'Đã cập nhật gói thành công',
    
    // Admin Banks
    'admin.banks.title': 'Quản Lý Ngân Hàng',
    'admin.banks.createBank': 'Thêm Ngân Hàng',
    'admin.banks.editBank': 'Chỉnh Sửa Ngân Hàng',
    'admin.banks.name': 'Tên Ngân Hàng',
    'admin.banks.code': 'Mã Ngân Hàng',
    'admin.banks.iconUrl': 'URL Icon',
    'admin.banks.bankCreated': 'Đã thêm ngân hàng thành công',
    'admin.banks.bankUpdated': 'Đã cập nhật ngân hàng thành công',
    
    // Admin Actions
    'admin.actions.create': 'Tạo Mới',
    'admin.actions.edit': 'Chỉnh Sửa',
    'admin.actions.delete': 'Xóa',
    'admin.actions.save': 'Lưu',
    'admin.actions.cancel': 'Hủy',
    'admin.actions.search': 'Tìm Kiếm',
    'admin.actions.filter': 'Lọc',
    'admin.actions.export': 'Xuất',
    'admin.actions.refresh': 'Làm Mới',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('app_lang');
    return (saved as Language) || 'vi';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app_lang', lang);
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
